### ISSUE TITLE
Decide support of Windows for CLI

### ISSUE THREAD

**Issue by lkostrowski** [saleor/cli#508]
Decide if windows is supported natively or by WSL

Add note to documentation about support and requirements for windows

**Comment by lkostrowski** [comment]
@patrys do you have opinion?

**Comment by patrys** [comment]
Is there a technical limitation to prefer either way? I think it's fair to target Windows versions that include WSL as WSL2 is also required for Docker desktop.

**Comment by lkostrowski** [comment]
@patrys I think WSL will work out of the box, we only need to make it clear in docs. 

In case of native windows shell we will need to have some more complex flow (testing on windows, extra time, branching code).

We'd like to stick to WSL + docs, maybe if community request native windows, we can add support in the future

**Comment by lkostrowski** [comment]
@lkostrowski to write ADR
